------------------------------------------------------------------
-- Top module (integration level)
--
-- Goal:
--   Integrate all IPs of the ground drone project:
--     - PWM: generates three reference PWM waveforms (95/50/15% duty cycles)
--     - BPStartStop: toggles the global "move" enable using the start button
--     - Direction: selects which PWM reference drives each motor according to
--                  sensor inputs + move enable, and outputs mode encodings
--     - SevenSegmentDisplay: displays the selected modes on the 4-digit 7-seg
--
-- Inputs:
--   clk        : 50 MHz system clock (Basys3)
--   reset      : asynchronous active-high reset
--   sensorLeft : IR sensor (1 when black detected, 0 otherwise)
--   sensorRight: IR sensor (1 when black detected, 0 otherwise)
--   ButtonStart: push button used to toggle start/stop
--
-- Outputs:
--   motorLeft  : PWM motor command for left motor
--   motorRight : PWM motor command for right motor
--   seg        : cathodes (active-low) for 7-seg segments a..g
--   an         : anodes (active-low) to select one digit among 4
------------------------------------------------------------------

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity Top is
  Port (
    clk : in std_logic;
    reset : in std_logic;

    sensorLeft : in std_logic;
    sensorRight : in std_logic;

    ButtonStart : in std_logic;

    motorLeft : out std_logic;
    motorRight : out std_logic;
    seg : out std_logic_vector(6 downto 0);
    an : out std_logic_vector(3 downto 0)
  );
end Top;

architecture Behavioral of Top is

    -- Internal reference PWM signals generated by the PWM IP.
    -- These are not sent directly to motors: Direction selects
    -- one of them for each motor depending on sensor states.

    signal pwm_fst_s : std_logic;  -- fast PWM reference  (95% duty cycle)
    signal pwm_std_s : std_logic;  -- standard reference  (50% duty cycle)
    signal pwm_slw_s : std_logic;  -- slow PWM reference  (15% duty cycle)

    -- Global enable signal from StartStop IP.
    -- move_s = 1 => drone is allowed to move
    -- move_s = 0 => motors are forced to stop (safe state)

    signal move_s : std_logic;

    -- Mode encodings produced by Direction (2-bit per motor).
    -- Used by SevenSegmentDisplay:
    --   "00" stop, "01" slow, "10" standard, "11" fast

    signal mode_right_s : std_logic_vector(1 downto 0);
    signal mode_left_s : std_logic_vector(1 downto 0);

begin

    -- PWM IP instantiation
    -- Generates three reference PWM waveforms for the speed levels.

    I_PWM: entity work.PWM
        port map (
            clk => clk,
            reset => reset,
            pwm_fst => pwm_fst_s,
            pwm_std => pwm_std_s,
            pwm_slw => pwm_slw_s
        );

    -- Start/Stop IP instantiation
    -- Toggles the global move enable each time the button is pressed.

    I_BPStartStop: entity work.BPStartStop
        port map (
            clk => clk,
            reset => reset,
            button => ButtonStart,
            move => move_s
        );

    -- Direction IP instantiation
    -- Selects which PWM reference drives each motor according to:
    --   - sensorLeft/sensorRight (line detection)
    --   - move_s (start/stop enable)
    -- Also outputs mode encodings for the 7-segment display.

    I_Direction: entity work.Direction
        port map (
            clk => clk,
            reset => reset,
            refPwmFst => pwm_fst_s,
            refPwmStd => pwm_std_s,
            refPwmSlw => pwm_slw_s,
            sensorLeft => sensorLeft,
            sensorRight => sensorRight,
            state_move => move_s,
            motorLeft => motorLeft,
            motorRight => motorRight,
            mode_right => mode_right_s,
            mode_left => mode_left_s
        );

    -- Seven-segment display IP instantiation
    -- Displays the selected motor modes (0..3) on the 4 digits.

    I_SevenSegment: entity work.SevenSegmentDisplay
        port map (
            clk => clk,
            reset => reset,
            mode_right => mode_right_s,
            mode_left => mode_left_s,
            seg => seg,
            an => an
        );

end Behavioral;
